create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 200),
  assignee text not null check (assignee in ('Michaila', 'Brady')),
  due date,
  project text not null default 'General',
  recurring boolean not null default false,
  frequency text not null default 'monthly' check (frequency in ('weekly', 'monthly', 'quarterly', 'yearly')),
  paused boolean not null default false,
  recurrence_generated boolean not null default false,
  status text not null default 'todo' check (status in ('todo', 'doing', 'waiting')),
  note text not null default '' check (char_length(note) <= 180),
  completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.tasks enable row level security;

create policy "Tasktracker users can read tasks"
on public.tasks for select to anon using (true);

create policy "Tasktracker users can create tasks"
on public.tasks for insert to anon with check (true);

create policy "Tasktracker users can update tasks"
on public.tasks for update to anon using (true) with check (true);

create policy "Tasktracker users can delete tasks"
on public.tasks for delete to anon using (true);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tasks_set_updated_at on public.tasks;
create trigger tasks_set_updated_at before update on public.tasks
for each row execute function public.set_updated_at();
