-- Tasktracker schema.
--
-- This file is idempotent: run the whole thing in the Supabase SQL Editor on a
-- brand new project OR on an existing one. Re-running it upgrades an older
-- database in place without touching your data.
--
-- Order matters: profiles and projects are created before tasks, because tasks
-- carries foreign keys into both.

-- ---------------------------------------------------------------------------
-- profiles
-- ---------------------------------------------------------------------------

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  role text not null default 'member' check (role in ('member', 'admin')),
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists title text not null default '';
alter table public.profiles add column if not exists office text not null default '';
alter table public.profiles add column if not exists accent text not null default 'lavender';
alter table public.profiles add column if not exists active boolean not null default true;
alter table public.profiles add column if not exists sort_order integer not null default 100;

alter table public.profiles drop constraint if exists profiles_accent_check;
alter table public.profiles add constraint profiles_accent_check
  check (accent in ('coral', 'teal', 'blue', 'lavender', 'amber', 'rose'));

alter table public.profiles enable row level security;

-- ---------------------------------------------------------------------------
-- invitations
--
-- Who is allowed to create an account, and what their profile should say when
-- they do. The administrator adds a row per teammate; that person then sets
-- their own password in the app. Nobody has to copy user UUIDs by hand, and an
-- email that is not listed here cannot join the workspace.
-- ---------------------------------------------------------------------------

create table if not exists public.invitations (
  email text primary key,
  display_name text not null,
  role text not null default 'member' check (role in ('member', 'admin')),
  title text not null default '',
  office text not null default '',
  accent text not null default 'lavender',
  sort_order integer not null default 100,
  created_at timestamptz not null default now(),
  claimed_at timestamptz,
  claimed_by uuid references auth.users(id) on delete set null
);

alter table public.invitations drop constraint if exists invitations_accent_check;
alter table public.invitations add constraint invitations_accent_check
  check (accent in ('coral', 'teal', 'blue', 'lavender', 'amber', 'rose'));

-- Addresses are compared case-insensitively, so store them one way.
create or replace function public.normalise_invitation_email()
returns trigger language plpgsql as $$
begin
  new.email = lower(trim(new.email));
  return new;
end;
$$;

drop trigger if exists invitations_normalise_email on public.invitations;
create trigger invitations_normalise_email before insert or update on public.invitations
for each row execute function public.normalise_invitation_email();

update public.invitations set email = lower(trim(email)) where email <> lower(trim(email));

alter table public.invitations enable row level security;

-- ---------------------------------------------------------------------------
-- projects
-- ---------------------------------------------------------------------------

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(name) between 1 and 80),
  description text not null default '' check (char_length(description) <= 160),
  due date,
  color text not null default 'teal' check (color in ('coral', 'blue', 'teal', 'lavender')),
  created_at timestamptz not null default now()
);

alter table public.projects add column if not exists updated_at timestamptz not null default now();
alter table public.projects add column if not exists archived boolean not null default false;

alter table public.projects enable row level security;

-- ---------------------------------------------------------------------------
-- tasks
-- ---------------------------------------------------------------------------

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 200),
  assignee text not null,
  due date,
  project text not null default 'General',
  recurring boolean not null default false,
  frequency text not null default 'monthly' check (frequency in ('weekly', 'monthly', 'quarterly', 'yearly')),
  paused boolean not null default false,
  recurrence_generated boolean not null default false,
  status text not null default 'todo' check (status in ('todo', 'doing', 'waiting')),
  note text not null default '',
  completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.tasks add column if not exists priority text not null default 'normal';
alter table public.tasks add column if not exists completed_at timestamptz;
alter table public.tasks add column if not exists deleted_at timestamptz;
alter table public.tasks add column if not exists project_id bigint references public.projects(id) on delete set null;
alter table public.tasks add column if not exists assignee_id uuid references public.profiles(id) on delete set null;
alter table public.tasks add column if not exists created_by uuid references public.profiles(id) on delete set null;
alter table public.tasks add column if not exists updated_by uuid references public.profiles(id) on delete set null;

-- The original schema hardcoded two names into a check constraint, so hiring a
-- third person required a migration. Assignee is now validated by length only;
-- the app offers the choices from public.profiles.
alter table public.tasks drop constraint if exists tasks_assignee_check;
alter table public.tasks add constraint tasks_assignee_check
  check (char_length(assignee) between 1 and 80);

alter table public.tasks drop constraint if exists tasks_priority_check;
alter table public.tasks add constraint tasks_priority_check
  check (priority in ('low', 'normal', 'high'));

-- Handoff notes were capped at 180 characters, which truncated mid-sentence.
alter table public.tasks drop constraint if exists tasks_note_check;
alter table public.tasks add constraint tasks_note_check
  check (char_length(note) <= 400);

alter table public.tasks enable row level security;

-- ---------------------------------------------------------------------------
-- notes
-- ---------------------------------------------------------------------------

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  entity_type text not null check (entity_type in ('task', 'project')),
  entity_id bigint not null,
  body text not null check (char_length(body) between 1 and 1000),
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  created_at timestamptz not null default now()
);

alter table public.notes enable row level security;

-- ---------------------------------------------------------------------------
-- task_activity
--
-- Who changed what, and when. An accounting team needs to be able to answer
-- that after the fact; before this table the only record of a reassignment or a
-- due-date change was the value itself.
-- ---------------------------------------------------------------------------

create table if not exists public.task_activity (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  actor_name text not null default '',
  action text not null,
  detail text not null default '',
  created_at timestamptz not null default now()
);

alter table public.task_activity enable row level security;

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

create index if not exists tasks_open_due_idx
  on public.tasks (completed, due) where deleted_at is null;
create index if not exists tasks_assignee_idx
  on public.tasks (assignee) where deleted_at is null;
create index if not exists tasks_project_id_idx
  on public.tasks (project_id) where deleted_at is null;
create index if not exists tasks_recurring_idx
  on public.tasks (recurring, paused) where completed = false and deleted_at is null;
create index if not exists tasks_updated_at_idx
  on public.tasks (updated_at desc);
-- The shape of the query the app runs every five seconds:
-- tasks?deleted_at=is.null&order=created_at.asc
create index if not exists tasks_active_created_idx
  on public.tasks (created_at) where deleted_at is null;
create index if not exists notes_entity_idx
  on public.notes (entity_type, entity_id, created_at);
create index if not exists task_activity_task_idx
  on public.task_activity (task_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tasks_set_updated_at on public.tasks;
create trigger tasks_set_updated_at before update on public.tasks
for each row execute function public.set_updated_at();

drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at before update on public.projects
for each row execute function public.set_updated_at();

-- Keeps the denormalised text columns and the foreign keys agreeing with each
-- other, and stamps completed_at / created_by / updated_by. The app writes
-- names; the database resolves them to ids.
create or replace function public.tasks_sync_links()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  select id into new.project_id from public.projects where name = new.project;
  select id into new.assignee_id from public.profiles where display_name = new.assignee;

  if tg_op = 'INSERT' then
    new.created_by = coalesce(new.created_by, auth.uid());
    new.updated_by = coalesce(new.updated_by, auth.uid());
    if new.completed and new.completed_at is null then
      new.completed_at = now();
    end if;
  else
    new.updated_by = auth.uid();
    if new.completed and not old.completed then
      new.completed_at = now();
    elsif not new.completed and old.completed then
      new.completed_at = null;
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists tasks_sync_links_trigger on public.tasks;
create trigger tasks_sync_links_trigger before insert or update on public.tasks
for each row execute function public.tasks_sync_links();

-- Renaming a project used to orphan every task pointing at the old name.
create or replace function public.projects_cascade_rename()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.name is distinct from old.name then
    -- Match on the old name as well: a task written before project_id existed,
    -- or one whose project was created after it, carries a null project_id and
    -- would otherwise keep pointing at a name nobody uses any more.
    update public.tasks
    set project = new.name
    where project_id = new.id or (project_id is null and project = old.name);
  end if;
  return new;
end;
$$;

drop trigger if exists projects_cascade_rename_trigger on public.projects;
create trigger projects_cascade_rename_trigger after update on public.projects
for each row execute function public.projects_cascade_rename();

-- notes.entity_id is polymorphic, so it cannot carry a foreign key. Clean up by
-- hand instead of leaving orphaned notes behind.
create or replace function public.notes_cleanup()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  delete from public.notes
  where entity_type = tg_argv[0] and entity_id = old.id;
  return old;
end;
$$;

drop trigger if exists tasks_notes_cleanup on public.tasks;
create trigger tasks_notes_cleanup after delete on public.tasks
for each row execute function public.notes_cleanup('task');

drop trigger if exists projects_notes_cleanup on public.projects;
create trigger projects_notes_cleanup after delete on public.projects
for each row execute function public.notes_cleanup('project');

-- Activity log.
create or replace function public.tasks_log_activity()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  who text;
begin
  select display_name into who from public.profiles where id = auth.uid();
  who = coalesce(who, 'Someone');

  if tg_op = 'INSERT' then
    insert into public.task_activity (task_id, actor_id, actor_name, action, detail)
    values (new.id, auth.uid(), who, 'created', new.name);
    return new;
  end if;

  if new.deleted_at is not null and old.deleted_at is null then
    insert into public.task_activity (task_id, actor_id, actor_name, action, detail)
    values (new.id, auth.uid(), who, 'deleted', '');
  elsif new.deleted_at is null and old.deleted_at is not null then
    insert into public.task_activity (task_id, actor_id, actor_name, action, detail)
    values (new.id, auth.uid(), who, 'restored', '');
  end if;

  if new.completed is distinct from old.completed then
    insert into public.task_activity (task_id, actor_id, actor_name, action, detail)
    values (new.id, auth.uid(), who, case when new.completed then 'completed' else 'reopened' end, '');
  end if;

  if new.assignee is distinct from old.assignee then
    insert into public.task_activity (task_id, actor_id, actor_name, action, detail)
    values (new.id, auth.uid(), who, 'reassigned', old.assignee || ' to ' || new.assignee);
  end if;

  if new.due is distinct from old.due then
    insert into public.task_activity (task_id, actor_id, actor_name, action, detail)
    values (new.id, auth.uid(), who, 'due date',
            coalesce(old.due::text, 'none') || ' to ' || coalesce(new.due::text, 'none'));
  end if;

  if new.status is distinct from old.status then
    insert into public.task_activity (task_id, actor_id, actor_name, action, detail)
    values (new.id, auth.uid(), who, 'status', old.status || ' to ' || new.status);
  end if;

  if new.name is distinct from old.name then
    insert into public.task_activity (task_id, actor_id, actor_name, action, detail)
    values (new.id, auth.uid(), who, 'renamed', new.name);
  end if;

  if new.priority is distinct from old.priority then
    insert into public.task_activity (task_id, actor_id, actor_name, action, detail)
    values (new.id, auth.uid(), who, 'priority', old.priority || ' to ' || new.priority);
  end if;

  -- Keyed off project_id, not the text column, so renaming a project does not
  -- log a move on every task that belongs to it.
  if new.project_id is distinct from old.project_id then
    insert into public.task_activity (task_id, actor_id, actor_name, action, detail)
    values (new.id, auth.uid(), who, 'moved',
            coalesce(old.project, 'none') || ' to ' || coalesce(new.project, 'none'));
  end if;

  return new;
end;
$$;

drop trigger if exists tasks_log_activity_trigger on public.tasks;
create trigger tasks_log_activity_trigger after insert or update on public.tasks
for each row execute function public.tasks_log_activity();

-- ---------------------------------------------------------------------------
-- Account creation
--
-- Signing up is gated on an invitation. When an invited address creates an
-- account, its profile is written for it and the invitation is marked claimed.
-- An address with no invitation gets an auth user with no profile, which every
-- policy below refuses, and the app tells them to ask the administrator.
-- ---------------------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  invite public.invitations%rowtype;
begin
  select * into invite
  from public.invitations
  where email = lower(trim(new.email)) and claimed_at is null;

  if not found then
    return new;
  end if;

  insert into public.profiles (id, display_name, role, title, office, accent, sort_order)
  values (new.id, invite.display_name, invite.role, invite.title, invite.office, invite.accent, invite.sort_order)
  on conflict (id) do nothing;

  update public.invitations
  set claimed_at = now(), claimed_by = new.id
  where email = invite.email;

  return new;
exception when others then
  -- Never let a provisioning problem turn into "Database error saving new
  -- user". The account is created without a profile, which is a state the app
  -- already explains, and the administrator can repair it with one insert.
  raise warning 'handle_new_user failed for %: %', new.email, sqlerrm;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

/*
 * Lets the sign-up screen say "that address has not been invited" before it
 * creates anything. Returns a boolean and nothing else, so it cannot be used
 * to read the invitation list.
 */
create or replace function public.email_is_invited(check_email text)
returns boolean language sql security definer set search_path = public stable as $$
  select exists (
    select 1 from public.invitations
    where email = lower(trim(check_email)) and claimed_at is null
  );
$$;

revoke all on function public.email_is_invited(text) from public;
grant execute on function public.email_is_invited(text) to anon, authenticated;

/*
 * Membership is having a profile row, not merely holding a token. Every policy
 * below is written in terms of this, so an account that signed up without an
 * invitation can read nothing.
 */
create or replace function public.is_workspace_member()
returns boolean language sql security definer set search_path = public stable as $$
  select exists (select 1 from public.profiles where id = auth.uid());
$$;

create or replace function public.is_workspace_admin()
returns boolean language sql security definer set search_path = public stable as $$
  select exists (
    select 1 from public.profiles where id = auth.uid() and role = 'admin'
  );
$$;

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------

drop policy if exists "Tasktracker users can read tasks" on public.tasks;
drop policy if exists "Tasktracker users can create tasks" on public.tasks;
drop policy if exists "Tasktracker users can update tasks" on public.tasks;
drop policy if exists "Tasktracker users can delete tasks" on public.tasks;
drop policy if exists "Users can read their own profile" on public.profiles;
drop policy if exists "Signed-in users can read profiles" on public.profiles;
drop policy if exists "Users can update their own profile" on public.profiles;
drop policy if exists "Signed-in users can read tasks" on public.tasks;
drop policy if exists "Signed-in users can create tasks" on public.tasks;
drop policy if exists "Signed-in users can update tasks" on public.tasks;
drop policy if exists "Signed-in users can delete tasks" on public.tasks;
drop policy if exists "Admins can delete tasks" on public.tasks;
drop policy if exists "Signed-in users can read projects" on public.projects;
drop policy if exists "Signed-in users can create projects" on public.projects;
drop policy if exists "Signed-in users can update projects" on public.projects;
drop policy if exists "Signed-in users can delete projects" on public.projects;
drop policy if exists "Signed-in users can read notes" on public.notes;
drop policy if exists "Signed-in users can create notes" on public.notes;
drop policy if exists "Authors and admins can delete notes" on public.notes;
drop policy if exists "Signed-in users can read activity" on public.task_activity;
drop policy if exists "Admins can read invitations" on public.invitations;
drop policy if exists "Admins can manage invitations" on public.invitations;

-- Every signed-in user can see the roster. The old policy exposed only your own
-- row, which is why the team list and the assignee menus had to be hardcoded.
create policy "Signed-in users can read profiles"
on public.profiles for select to authenticated using (public.is_workspace_member());

create policy "Signed-in users can read tasks"
on public.tasks for select to authenticated using (public.is_workspace_member());

create policy "Signed-in users can create tasks"
on public.tasks for insert to authenticated with check (public.is_workspace_member());

create policy "Signed-in users can update tasks"
on public.tasks for update to authenticated using (public.is_workspace_member()) with check (public.is_workspace_member());

-- Everyday deletion is a soft delete (deleted_at), which is what makes Undo
-- work. Permanent removal is an admin action.
create policy "Admins can delete tasks"
on public.tasks for delete to authenticated using (public.is_workspace_admin());

create policy "Signed-in users can read projects"
on public.projects for select to authenticated using (public.is_workspace_member());

create policy "Signed-in users can create projects"
on public.projects for insert to authenticated with check (public.is_workspace_member());

create policy "Signed-in users can update projects"
on public.projects for update to authenticated using (public.is_workspace_member()) with check (public.is_workspace_member());

create policy "Signed-in users can delete projects"
on public.projects for delete to authenticated using (public.is_workspace_member());

create policy "Signed-in users can read notes"
on public.notes for select to authenticated using (public.is_workspace_member());

create policy "Signed-in users can create notes"
on public.notes for insert to authenticated
with check (author_id = auth.uid() and public.is_workspace_member());

create policy "Authors and admins can delete notes"
on public.notes for delete to authenticated using (
  author_id = auth.uid() or public.is_workspace_admin()
);

create policy "Signed-in users can read activity"
on public.task_activity for select to authenticated using (public.is_workspace_member());

-- Nobody touches the invitation list through the API except an administrator.
-- Everyone else goes through public.email_is_invited, which returns a boolean.
create policy "Admins can manage invitations"
on public.invitations for all to authenticated
using (public.is_workspace_admin()) with check (public.is_workspace_admin());

-- ---------------------------------------------------------------------------
-- Backfill
-- ---------------------------------------------------------------------------

update public.tasks t set project_id = p.id
from public.projects p where p.name = t.project and t.project_id is null;

update public.tasks t set assignee_id = pr.id
from public.profiles pr where pr.display_name = t.assignee and t.assignee_id is null;

update public.tasks set completed_at = updated_at
where completed and completed_at is null;

-- Anyone already using the workspace keeps working: record their invitation as
-- claimed so the roster and the invitation list agree with each other.
insert into public.invitations (email, display_name, role, title, office, accent, sort_order, claimed_at, claimed_by)
select lower(trim(users.email)), profiles.display_name, profiles.role, profiles.title,
       profiles.office, profiles.accent, profiles.sort_order, now(), profiles.id
from public.profiles
join auth.users on users.id = profiles.id
where users.email is not null
on conflict (email) do nothing;

-- ---------------------------------------------------------------------------
-- Confirm setup. Expect six rows: invitations, notes, profiles, projects,
-- task_activity, tasks.
-- ---------------------------------------------------------------------------

select schemaname, tablename
from pg_tables
where schemaname = 'public'
  and tablename in ('invitations', 'notes', 'profiles', 'projects', 'task_activity', 'tasks')
order by tablename;
